### PR TITLE
SDM72 Register Map fix

### PR DESCRIPTION
**Pull request by thokis**
Regarding [this issue](https://github.com/nmakel/sdm_modbus/issues/9). I extended `self.registers` from SDM72 Class so now read_all() should return all input registers.

### CODE REVIEW

**Comment by nmakel** [comment]
Thanks for the patch. Can you confirm the registers actually contain data?

**Comment by thokis** [comment]
They contain values but to be honest i did not test it with `read_all()`. I assumed it should return everything. Using a modified version of `example-rtu.py` where the meter is an `SDM72` object i can not see them and also manually using `read_all()` it does not work. Using a modbus client like [uModbus](https://umodbus.readthedocs.io/en/latest/index.html) and reading each register i get valid data. Here is the output of the client using the registers dictionary from `SDM72`:
```
REGISTER=l1_voltage, ADDR=[0x0,0x1], DATA=[17258, 44790], VALUE=234.68V
REGISTER=l2_voltage, ADDR=[0x2,0x3], DATA=[0, 0], VALUE=0.00V
REGISTER=l3_voltage, ADDR=[0x4,0x5], DATA=[0, 0], VALUE=0.00V
REGISTER=l1_current, ADDR=[0x6,0x7], DATA=[15773, 52700], VALUE=0.08A
REGISTER=l2_current, ADDR=[0x8,0x9], DATA=[0, 0], VALUE=0.00A
REGISTER=l3_current, ADDR=[0xa,0xb], DATA=[0, 0], VALUE=0.00A
REGISTER=l1_power_active, ADDR=[0xc,0xd], DATA=[16688, 23770], VALUE=11.02W
REGISTER=l2_power_active, ADDR=[0xe,0xf], DATA=[0, 0], VALUE=0.00W
REGISTER=l3_power_active, ADDR=[0x10,0x11], DATA=[0, 0], VALUE=0.00W
REGISTER=l1_power_apparent, ADDR=[0x12,0x13], DATA=[16782, 33855], VALUE=17.81VA
REGISTER=l2_power_apparent, ADDR=[0x14,0x15], DATA=[0, 0], VALUE=0.00VA
REGISTER=l3_power_apparent, ADDR=[0x16,0x17], DATA=[0, 0], VALUE=0.00VA
REGISTER=l1_power_reactive, ADDR=[0x18,0x19], DATA=[16736, 13070], VALUE=14.01VAr
REGISTER=l2_power_reactive, ADDR=[0x1a,0x1b], DATA=[0, 0], VALUE=0.00VAr
REGISTER=l3_power_reactive, ADDR=[0x1c,0x1d], DATA=[0, 0], VALUE=0.00VAr
REGISTER=l1_power_factor, ADDR=[0x1e,0x1f], DATA=[16156, 60761], VALUE=0.61
REGISTER=l2_power_factor, ADDR=[0x20,0x21], DATA=[0, 0], VALUE=0.00
REGISTER=l3_power_factor, ADDR=[0x22,0x23], DATA=[0, 0], VALUE=0.00
REGISTER=voltage_ln, ADDR=[0x2a,0x2b], DATA=[17052, 24759], VALUE=78.19V
REGISTER=current_ln, ADDR=[0x2e,0x2f], DATA=[15568, 32144], VALUE=0.03A
REGISTER=total_line_current, ADDR=[0x30,0x31], DATA=[15772, 62174], VALUE=0.08A
REGISTER=total_power, ADDR=[0x34,0x35], DATA=[16687, 36802], VALUE=10.97W
REGISTER=total_power_apparent, ADDR=[0x38,0x39], DATA=[16781, 44026], VALUE=17.71VA
REGISTER=total_power_reactive, ADDR=[0x3c,0x3d], DATA=[16734, 40008], VALUE=13.91VAr
REGISTER=total_pf, ADDR=[0x3e,0x3f], DATA=[16157, 11291], VALUE=0.61
REGISTER=frequency, ADDR=[0x46,0x47], DATA=[16968, 2621], VALUE=50.01Hz
REGISTER=import_energy_active, ADDR=[0x48,0x49], DATA=[16020, 65012], VALUE=0.29kWh
REGISTER=export_energy_active, ADDR=[0x4a,0x4b], DATA=[0, 0], VALUE=0.00kWh
REGISTER=l12_voltage, ADDR=[0xc8,0xc9], DATA=[17355, 12205], VALUE=406.37V
REGISTER=l23_voltage, ADDR=[0xca,0xcb], DATA=[0, 0], VALUE=0.00V
REGISTER=l31_voltage, ADDR=[0xcc,0xcd], DATA=[0, 0], VALUE=0.00V
REGISTER=voltage_ll, ADDR=[0xce,0xcf], DATA=[17159, 30972], VALUE=135.47V
REGISTER=neutral_current, ADDR=[0xe0,0xe1], DATA=[15772, 4061], VALUE=0.08A
REGISTER=total_energy_active, ADDR=[0x156,0x157], DATA=[16020, 65012], VALUE=0.29kWh
REGISTER=total_energy_reactive, ADDR=[0x158,0x159], DATA=[16065, 1573], VALUE=0.38kVArh
REGISTER=resettable_total_energy_active, ADDR=[0x180,0x181], DATA=[16020, 65012], VALUE=0.29kWh
REGISTER=resettable_import_enerty_active, ADDR=[0x184,0x185], DATA=[16020, 65012], VALUE=0.29kWh
REGISTER=resettable_export_energy_active, ADDR=[0x186,0x187], DATA=[0, 0], VALUE=0.00kWh
REGISTER=net_kwh, ADDR=[0x18c,0x18d], DATA=[16020, 65012], VALUE=0.29kWh
REGISTER=import_total_power_active, ADDR=[0x500,0x501], DATA=[16687, 20876], VALUE=10.96W
REGISTER=export_total_power_active, ADDR=[0x502,0x503], DATA=[32768, 0], VALUE=-0.00W
REGISTER=demand_time, ADDR=[0x0,0x1], DATA=[0, 0], VALUE=0.00s
REGISTER=demand_period, ADDR=[0x2,0x3], DATA=[0, 0], VALUE=0.00s
REGISTER=system_voltage, ADDR=[0x6,0x7], DATA=[0, 0], VALUE=0.00V
REGISTER=system_current, ADDR=[0x8,0x9], DATA=[0, 0], VALUE=0.00A
REGISTER=system_type, ADDR=[0xa,0xb], DATA=[16448, 0], VALUE=3.00[-1, '1P2W', '3P3W', '3P4W']
REGISTER=relay_pulse_width, ADDR=[0xc,0xd], DATA=[16908, 0], VALUE=35.00ms
REGISTER=network_parity_stop, ADDR=[0x12,0x13], DATA=[0, 0], VALUE=0.00['N-1', 'E-1', 'O-1', 'N-2']
REGISTER=meter_id, ADDR=[0x14,0x15], DATA=[16256, 0], VALUE=1.00
REGISTER=password, ADDR=[0x18,0x19], DATA=[17530, 0], VALUE=1000.00
REGISTER=baud, ADDR=[0x1c,0x1d], DATA=[16448, 0], VALUE=3.00[2400, 4800, 9600, 19200, 38400]
REGISTER=system_power, ADDR=[0x24,0x25], DATA=[0, 0], VALUE=0.00W
REGISTER=p1_divisor, ADDR=[0xf910,0xf911], DATA=[0, 0], VALUE=0.00['0.001kWh/imp', '0.01kWh/imp', '0.1kWh/imp', '1kWh/imp', '10kWh/imp', '100kWh/imp']
```

So at the end i think there is something wrong with the `read_all()` method from class `Meter`

**Comment by nmakel** [comment]
What output or errors are you getting from `examply-rtu.py` with the SDM72? The output you posted looks fine for a 3 phase meter with only a single phase connected.

**Comment by thokis** [comment]
I do not get any errors, the example works fine in that way. The problem is output is incomplete. For example `python3 example-rtu.py /dev/tty.usbserial-AI0483CW --baud 19200 --unit 1 --parity N --stopbits 1` gives me this:
```
SDM72(/dev/tty.usbserial-AI0483CW, connectionType.RTU: stopbits=1, parity=N, baud=19200, timeout=1, retries=3, unit=0x1):

Input Registers:
	L1 Voltage: 235.12V
	L2 Voltage: 0.00V
	L3 Voltage: 0.00V
	L1 Current: 1.08A
	L2 Current: 0.00A
	L3 Current: 0.00A
	L1 Power (Active): 54.96W
	L2 Power (Active): 0.00W
	L3 Power (Active): 0.00W
	L1 Power (Apparent): 145.38VA
	L2 Power (Apparent): 0.00VA
	L3 Power (Apparent): 0.00VA
	L1 Power (Reactive): 134.59VAr
	L2 Power (Reactive): 0.00VAr
	L3 Power (Reactive): 0.00VAr
	L1 Power Factor: 0.38
	L2 Power Factor: 0.00
	L3 Power Factor: 0.00
	L-N Voltage: 78.37V
	L-N Current: 0.36A
	Total Line Current: 1.08A
	Total Power: 54.96W
	Total Power (Apparent): 145.38VA
	Total Power (Reactive): 134.59VAr
	Total Power Factor: 0.38
	Frequency: 50.00Hz
	Imported Energy (Active): 0.30kWh
	Exported Energy (Active): 0.00kWh

Holding Registers:
	Demand Time: 0s
	Demand Period: 0s
	System Voltage: 0.00V
	System Current: 0.00A
	System Type: 3P4W
	Relay Pulse Width: 35ms
	Network Parity Stop: N-1
	Meter ID: 1
	Password: 1000
	Baud Rate: 19200
	System Power: 0.00W
	P1 Divisor: 0.001kWh/imp
```

And here is some python 3.9 `REPL` output:
```python
Python 3.9.9 (main, Nov 21 2021, 03:23:42) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdm_modbus
>>> device = sdm_modbus.SDM72(device='/dev/tty.usbserial-AI0483CW', baud=19200, parity='N', stopbits=1)
>>> device.read_all()
{'l1_voltage': 234.6852569580078, 'l2_voltage': 0.0, 'l3_voltage': 0.0, 'l1_current': 1.1135060787200928, 'l2_current': 0.0, 'l3_current': 0.0, 'l1_power_active': 57.36007308959961, 'l2_power_active': 0.0, 'l3_power_active': 0.0, 'l1_power_apparent': 150.20431518554688, 'l2_power_apparent': 0.0, 'l3_power_apparent': 0.0, 'l1_power_reactive': 138.8206024169922, 'l2_power_reactive': 0.0, 'l3_power_reactive': 0.0, 'l1_power_factor': 0.3818803131580353, 'l2_power_factor': 0.0, 'l3_power_factor': 0.0, 'voltage_ln': 78.2284164428711, 'current_ln': 0.37116870284080505, 'total_line_current': 1.1135060787200928, 'total_power': 57.36007308959961, 'total_power_apparent': 150.20431518554688, 'total_power_reactive': 138.8206024169922, 'total_pf': 0.3818803131580353, 'frequency': 49.95000076293945, 'import_energy_active': 0.3050000071525574, 'export_energy_active': 0.0}
>>> for i in device.read_all():
...     counter += 1
... 
>>> print(counter)
28
>>>
```
There are 40 `meter.registerType.INPUT` entries in `self.registers` from `SDM72` class but only 28 returned from `read_all()`.

**Comment by nmakel** [comment]
Updated the SDM72 register batching. Please try again.

**Comment by thokis** [comment]
Yeah it works now. Actually there are 41 `meter.registerType.INPUT` entries in `self.registers`.

**Pull request merged**
