### PR TITLE
Add GARO meter support

### PR DESCRIPTION
**Pull request by ksjoberg**
Is this along the lines you were thinking?

### CODE REVIEW

**Comment by nmakel** [comment]
Thanks! I'll have a look at the changes when I have a bit more time. The switch to poetry is not something I had considered before, so will need to experiment first.

**Comment by ksjoberg** [comment]
I can refactor the poetry thing out separately, but since the testing libraries still needs to be pulled in, I found the alternative to be more cumbersome: a requirements.txt and a separate requirements_dev.txt with tox, behave and pyhamcrest, virtualenv management to set up the dev packages etc. I took a leap of faith in Poetry.

**Comment by nmakel** [comment]
Great additions, Kristoffer. I've done a rough merge which seems to pass all of the tests you've defined. I will probably be making a few adjustments to some of the formatting. I'm also not yet convinced about the `meter.registers` v.s. `meter.register_description` thing. In all it looks like a nice way to move towards supporting more similar meter devices! Thanks again :)

**Comment by ksjoberg** [comment]
No, I wasn't entirely happy with it either. I figured I either had to change your tuple or find a way to augment it. I'm not a fan of accessing through unnamed indices as the tuple solution mandates, but the pythonic way of declaring a list of dictionaries for each register was too verbose.

I have a unrelated change coming up that allows for batch-reading a subset of registers. As the SolarEdge inverter is very interested in current wattage readings, it makes sense to provide a way to read just those registers more frequently.

**Comment by nmakel** [comment]
> No, I wasn't entirely happy with it either. I figured I either had to change your tuple or find a way to augment it. I'm not a fan of accessing through unnamed indices as the tuple solution mandates, but the pythonic way of declaring a list of dictionaries for each register was too verbose.

I agree. The list of dicts felt much too bulky, while the tuple is too opaque. The solution I think is to keep and expand on the tuple, but ensure all of the utility (scaling, formatting and units) is accessible via class methods -- so users of the library are not impacted by future changes to it.

**Comment by nmakel** [comment]
> I have a unrelated change coming up that allows for batch-reading a subset of registers. As the SolarEdge inverter is very interested in current wattage readings, it makes sense to provide a way to read just those registers more frequently.

I saw the branch you refer to. I would suggest implementing that through a dedicated method, `read_batch` or `read_multiple`, for example. Not by modifying `read_all`. How do you propose changing `solaredge_meterproxy` to expose this functionality?

**Comment by nmakel** [comment]
One more question :)

There's a lot of overlap between `sdm_modbus` and `solaredge_modbus`, so I was reviewing some of the changes you made when moving to a base `Meter` class which might be appropriate to also apply to the other project. Specifically, `__init__()`:

```
    def __init__(
        self, **kwargs
    ):
        #host=False, port=False,
        #device=False, stopbits=False, parity=False, baud=False,
        #timeout=TIMEOUT, retries=RETRIES, unit=UNIT,
```

Is there any inherent advantage to using a arguments dict here? To me it feels like needlessly obfuscating what parameters are expected, evidenced by the need to keep a list in comment form right below.

**Comment by ksjoberg** [comment]
I'm a fan of IoC, so what I'd really like to do is to pull out the client initialization out of the meter class. Just keep the client argument and figure out a different way to initialize a Modbus client, whether it is a RTU, TCP or a mocked one in tests.￼ 

In such a scenario all those arguments being a union of all possible settings in the mutually exclusive operation modes would no longer be applicable.

To keep backwards compatibility is harder while keeping things neat, though.

**Pull request merged**
